spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:tmp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
#        show_sql: true
        format_sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 933042190897-ci7q9dkupuq9vapap70qgaca9rafib24.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
            - email
            - profile

          naver:
            client-id: JInPIm94AO7ZoE83O9wg
            client-secret: Y_H4L9vHbY
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email

          kakao:
            client-id: ded3ad1f49382d2c9f37d91bceaa41c3
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


jwt:
  jwt-key: "c7L0+z1bI67OpGIeYN9NcKgXBsHKiR2RlYX1Vzj4ULA="



